version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR2"
  phan:
    enabled: true
    config:
      file_extensions: "php"
      ignore-undeclared: true
  sonar-php:
    enabled: true
exclude_patterns:
- tests/
- .phan/
