engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
plugins:
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR2"
  phan:
    enabled: true
    config:
      file_extensions: "php"
  sonar-php:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/
