on:
  - pull_request
  - push

name: CI

jobs:
  tests:
    name: Tests

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        php:
          - "7.4"
          - "8.0"
          - "8.1"

    continue-on-error: ${{ matrix.php == '8.1' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov

      - name: Get composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer cache directory
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php }}-composer-

      - name: Install dependencies with composer
        run: |
          composer self-update
          composer update --no-ansi --no-interaction --no-progress

      - name: Run tests with phpunit
        run: vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml

      - name: Publish code coverage to codeclimate
        if: matrix.php == '8.0' && github.event_name == 'push'
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

